### PR TITLE
fu-engine: Clear activation flag on old firmware not new (Fixes: #1130)

### LINKED ISSUE #1130: activation flag removal doesn't save to history database
I've noticed that even after a succesful reboot + activation that the daemon isn't really clearing the activation flag from the history database.  It seems that the state isn't updating either.

```
05:44:58:0882 FuEngine             installed version 13000000 matching history 0.198.23872
05:44:58:0882 FuHistory            modifying device Disk [5dbeb140337f610d54913c0f43d15fdaa0eafb51], only version new 13000001
```

But then running get-history the activation flag is still there.
```
Disk
  DeviceId:             5dbeb140337f610d54913c0f43d15fdaa0eafb51
  Guid:                 cdfcae10-d678-5e2b-9742-d35891619fd2
  Plugin:               ata
  Flags:                internal|updatable|require-ac|needs-reboot|no-auto-instance-ids|needs-activation
  Version:              13000000
  Created:              2019-03-31
  UpdateState:          needs-reboot
  
  [Release]
  Version:              0.198.23873
  Checksum:             SHA1(39eadff89783818b44b09f1deff5e1034f53590d)
  Flags:                none
  CpuArchitecture:      x86_64
  RuntimeVersion(org.freedesktop.fwupd): 1.2.7
  DistroId:             ubuntu
  CompileVersion(org.freedesktop.fwupd): 1.2.7
  CompileVersion(com.redhat.fwupdate): 12
  CompileVersion(org.freedesktop.gusb): 0.2.11
  RuntimeVersion(org.freedesktop.appstream-glib): 0.7.14
  KernelVersion:        4.15.0-29-generic
  DistroVersion:        18.04
  CompileVersion(com.redhat.efivar): 34
  RuntimeVersion(com.dell.libsmbios): 2.4
  BootTime:             1553898087
  RuntimeVersion(com.redhat.fwupdate): 12

Disk
  DeviceId:             5dbeb140337f610d54913c0f43d15fdaa0eafb51
  Guid:                 cdfcae10-d678-5e2b-9742-d35891619fd2
  Plugin:               ata
  Flags:                internal|updatable|require-ac|needs-reboot|no-auto-instance-ids|needs-activation
  Version:              13000001
  Created:              2019-03-31
  UpdateState:          needs-reboot
  
  [Release]
  Version:              0.198.23872
  Checksum:             SHA1(96a508d36892d45bd702a20161ceb82b3c6f13f2)
  Flags:                none
  CpuArchitecture:      x86_64
  RuntimeVersion(org.freedesktop.fwupd): 1.2.7
  DistroId:             ubuntu
  CompileVersion(org.freedesktop.fwupd): 1.2.7
  CompileVersion(com.redhat.fwupdate): 12
  CompileVersion(org.freedesktop.gusb): 0.2.11
  RuntimeVersion(org.freedesktop.appstream-glib): 0.7.14
  KernelVersion:        4.15.0-29-generic
  DistroVersion:        18.04
  CompileVersion(com.redhat.efivar): 34
  RuntimeVersion(com.dell.libsmbios): 2.4
  BootTime:             1554062270
  RuntimeVersion(com.redhat.fwupdate): 12
```

### PR DESCRIPTION
**Pull request by superm1**
For me this seems to fix #1130 and match the right device.

Repro steps:
1. Clear pending.db
2. Start with ATA firmware X.
3. Flash ATA firmware Y.
4. Reboot machine (activate runs on shutdown)
5. Verify running on ATA firmware Y.
6. Verify that `fwupdmgr activate` return `No firmware to activate`.

Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/hughsie/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
That doesn't make sense tho, if the reboot comes up with the ATA device with the new version number then we want to match on the new version number, not the old one...

**Comment by superm1** [comment]
But you want to replace the history of the "old" one don't you?

**Comment by superm1** [comment]
One more time I cleared `pending.db` and went from firmware `13000001` to `13000000`.

Dumping from pending.db before the reboot.
```
sqlite> .headers on
sqlite> SELECT * FROM history;
device_id|update_state|update_error|filename|display_name|plugin|device_created|device_modified|checksum|flags|metadata|guid_default|version_old|version_new|checksum_device|protocol
5dbeb140337f610d54913c0f43d15fdaa0eafb51|4|||Disk|ata|1554300092|0|96a508d36892d45bd702a20161ceb82b3c6f13f2|1573131|CpuArchitecture=x86_64;RuntimeVersion(org.freedesktop.fwupd)=1.2.7;DistroId=ubuntu;CompileVersion(org.freedesktop.fwupd)=1.2.7;CompileVersion(com.redhat.fwupdate)=12;C
ompileVersion(org.freedesktop.gusb)=0.2.11;RuntimeVersion(org.freedesktop.appstream-glib)=0.7.14;KernelVersion=4.15.0-29-generic;DistroVersion=18.04;CompileVersion(com.redhat.efivar)=34;RuntimeVersion(com.dell.libsmbios)=2.4;BootTime=1554243115;RuntimeVersion(com.redhat.fwupdate)=12|cdfcae10-d678-5e2
b-9742-d35891619fd2|13000001|0.198.23872||
sqlite>.quit
# reboot
```

Here is the SQL command that runs right next time fwupd runs after reboot:
```
            UPDATE history SET update_state = 2, update_error = NULL, checksum_device = NULL, flags = 524555 WHERE device_id = '5dbeb140337f610d54913c0f43d15fdaa0eafb51' AND version_new = '13000001';
```

Even converting `0.198.23872` it would be `13000000`.  So it's definitely not going to find the right hit.  There does seem to be a logic error here somewhere.  If not the fix I said, it should probably be something like this (untested):

```
diff --git a/src/fu-history.c b/src/fu-history.c
index 3f94751c..f2c5bba3 100644
--- a/src/fu-history.c
+++ b/src/fu-history.c
@@ -439,6 +440,7 @@ fu_history_modify_device (FuHistory *self, FuDevice *device,
        gint rc;
        g_autoptr(sqlite3_stmt) stmt = NULL;
        g_autoptr(FuMutexLocker) locker = NULL;
+       FwuprRelease *release = fu_device_get_release_default (device);

        g_return_val_if_fail (FU_IS_HISTORY (self), FALSE);
        g_return_val_if_fail (FU_IS_DEVICE (device), FALSE);
@@ -476,6 +478,7 @@ fu_history_modify_device (FuHistory *self, FuDevice *device,
                                         "flags = ?3 "
                                         "WHERE device_id = ?4 AND version_old = ?5;",
                                         -1, &stmt, NULL);
+               sqlite3_bind_text (stmt, 5, fu_device_get_version (device), -1, SQLITE_STATIC);
        } else if (flags & FU_HISTORY_FLAGS_MATCH_NEW_VERSION) {
                g_debug ("modifying device %s [%s], only version new %s",
                         fu_device_get_name (device),
@@ -489,6 +492,7 @@ fu_history_modify_device (FuHistory *self, FuDevice *device,
                                         "flags = ?3 "
                                         "WHERE device_id = ?4 AND version_new = ?5;",
                                         -1, &stmt, NULL);
+               sqlite3_bind_text (stmt, 5, fu_release_get_version (release), -1, SQLITE_STATIC);
        } else {
                g_assert_not_reached ();
        }
@@ -503,7 +507,6 @@ fu_history_modify_device (FuHistory *self, FuDevice *device,
        sqlite3_bind_text (stmt, 2, fu_device_get_update_error (device), -1, SQLITE_STATIC);
        sqlite3_bind_int64 (stmt, 3, fu_history_get_device_flags_filtered (device));
        sqlite3_bind_text (stmt, 4, fu_device_get_id (device), -1, SQLITE_STATIC);
-       sqlite3_bind_text (stmt, 5, fu_device_get_version (device), -1, SQLITE_STATIC);
        sqlite3_bind_text (stmt, 6, fwupd_checksum_get_by_kind (fu_device_get_checksums (device),
                                                                G_CHECKSUM_SHA1), -1, SQLITE_STATIC);
        return fu_history_stmt_exec (self, stmt, NULL, error);
```

**Comment by superm1** [comment]
That seems to work as well (and calls this).
```
UPDATE history SET update_state = 2, update_error = NULL, checksum_device = NULL, flags = 524555 WHERE device_id = '5dbeb140337f610d54913c0f43d15fdaa0eafb51' AND version_new = '0.198.23872';
```

**Comment by hughsie** [comment]
Just a random thought... Why is the version format different between the device and the release? Shouldn't there be a quirk somewhere?

**Comment by superm1** [comment]
> Just a random thought... Why is the version format different between the device and the release? Shouldn't there be a quirk somewhere?

This was a hand built-cab file, I didn't set the version format anywhere.  So internally this is what the daemon seems to be applying if no decimals are used in the version string.

**Comment by hughsie** [comment]
> I didn't set the version format anywhere

I think this is a bit fragile right now -- how about a warning/error if the release VersionFormat doesn't match the device VersionFormat?

**Comment by superm1** [comment]
> I think this is a bit fragile right now -- how about a warning/error if the release VersionFormat doesn't match the device VersionFormat?

Let me track down to see if they are actually storing in the release and device in this case.

**Comment by superm1** [comment]
I've added some new heuristics and warnings around these scenarios.

**Comment by superm1** [comment]
Can you take a look at this one?

**Comment by hughsie** [comment]
> Can you take a look at this one?

Sure, just doing so. I didn't like your heuristic at all, and am just paging all the details in so I can suggest something different.

**Comment by superm1** [comment]
Ok. Can you cherry pick the other fix if that looks ok? It's more important than the heuristic is and can follow up the heuristic later.

File: src/fu-engine.c [hunk 1]
```diff
@@ -4136,6 +4136,7 @@ fu_engine_update_history_device (FuEngine *self, FuDevice *dev_history, GError *
 			const gchar *csum = g_ptr_array_index (checksums, i);
 			fu_device_add_checksum (dev_history, csum);
 		}
+		fu_device_set_version (dev_history, fu_device_get_version (dev));
```
Comment (hughsie) [inline src/fu-engine.c]: What is the pending `version_new` and `version_old` values after the update has been applied and the user has rebooted? i.e. before `fu_engine_update_history_device()` runs? I think this might be papering over a bigger bug that needs some investigation first.

**Comment by hughsie** [comment]
I think having heuristics will drive us crazy. I'd much rather find the root cause of the bug with something like https://github.com/hughsie/fwupd/pull/1143 -- comments welcome.

File: src/fu-engine.c (hunk 1 above)
Comment (superm1) [reply src/fu-engine.c]: I cleared pending.db and I re-ran with the stuff in #1143 (after my fu-device donor fix for version format) but without my extra change in this PR.

Pending.db doesn't get updated at all.  Exact same content before and after reboot.
```
$ sqlite3 pending.db
SQLite version 3.22.0 2018-01-22 18:45:57
Enter ".help" for usage hints.
sqlite> .headers on
sqlite> select * from history;
device_id|update_state|update_error|filename|display_name|plugin|device_created|device_modified|checksum|flags|metadata|guid_default|version_old|version_new|checksum_device|protocol
5dbeb140337f610d54913c0f43d15fdaa0eafb51|4|||Micron 1300 SATA 256GB|ata|1554755186|0|722a4651af36cf770135e03d99193b826af8d0ac|1573131|CpuArchitecture=x86_64;RuntimeVersion(org.freedesktop
.fwupd)=1.2.7;DistroId=ubuntu;CompileVersion(org.freedesktop.fwupd)=1.2.7;CompileVersion(com.redhat.fwupdate)=12;CompileVersion(org.freedesktop.gusb)=0.2.11;RuntimeVersion(org.freedesktop
.appstream-glib)=0.7.14;KernelVersion=4.15.0-29-generic;DistroVersion=18.04;CompileVersion(com.redhat.efivar)=34;RuntimeVersion(com.dell.libsmbios)=2.4;BootTime=1554488415;RuntimeVersion(
com.redhat.fwupdate)=12|cdfcae10-d678-5e2b-9742-d35891619fd2|13000000|13000001||
```

Comment (hughsie) [reply src/fu-engine.c]: Seeing `|13000000|13000001|`... shouldn't we be saving the post-processed version in the history database? e.g. `0.198.23872`?

Comment (hughsie) [reply src/fu-engine.c]: Quick question; are you assuming that `fu_device_set_version()` is converting the format from `13000000` to `0.198.23872`? So far I've not done that, and the plugins have done that if they needed to...

Comment (superm1) [reply src/fu-engine.c]: I wouldn't expect that `fu_device_set_version` did conversion on it's own, but commits like https://github.com/hughsie/fwupd/commit/4bae7a2fa864fd6ff8091539fbaf896e1edf35ae were done to be impervious to the format being post-processed or not when compared.

Comment (superm1) [reply src/fu-engine.c]: I was under the assumption the version shouldn't be converted at all when the version_format was plain.

Comment (superm1) [reply src/fu-engine.c]: the message `installed version %s matching history %s` does match the "unprocessed" version though too.

Comment (hughsie) [reply src/fu-engine.c]: Wait, so you the version is expected to be shown as `13000000` and `0.198.23872` is the **wrong** format?

Comment (superm1) [reply src/fu-engine.c]: Yeah, I mean it's a plain version format, so that's what I expect to see and be used everywhere.  It's the format I see with get-devices, what I put in the XML file and what I expected to see in the history db (and am seeing right now)

Comment (hughsie) [reply src/fu-engine.c]: Okay, so that was a little wild-goose chase on my part then :)
